# Codecov Enterprise
# ==================
# Learn more at https://github.com/codecov/enterprise/wiki/Setup-codecov.yml
# Thank you! <3 the Codecov Team

setup:
    enterprise_company: null      # (required) provided by Codecov staff
    enterprise_license: null      # (required) provided by Codecov staff
    guest_access: false           # allow non-logged in users to view public repos
    loglvl: WARNING               # info, debug or warning
    cookie_secret: null           # (required) string used to encrypt secure cookies
    media_url: null               # (default) static files are served from Codecov's Amazon S3
                                  # (localhost) set value to 'localhost' to serve js/css/images locally
                                  # (advanced) set value to url to privatly hosting static files for advanced usage

services:
    database_url: null            # (required) postgres url
    redis_url: null               # (required) used for celery and storing reports before processing
    rabbitmq_url: null            # specify to use a rabbitmq as the celery broker
    logentries_token: null        # logging product interactions: https://logentries.com
    mailgun_endpoint: null        # Mailgun url to send system emails from
    google_analytics_key: null    # front-end tracking
    aws:
        access_key_id: null       #
        secret_access_key: null   #
        bucket: null              # bucket to store archived reports
        hash_key: null            # random string to encrypt upload path

# Github
# ---------------------------------
github:
    client_id: null               # (required) from https://github.com/settings/applications/new
    client_secret: null           # (required) from https://github.com/settings/applications/new
    access_token: null            # used to post comments, statuses, etc. Generate a full access token at https://github.com/settings/tokens/new
    organizations: null           # List of organizations. Users must be a member of at least one. (optional) (default all)
    global_upload_token: null     # a secret string that is used as a global token for uploading reports

# Github Enterprise
# ---------------------------------
github_enterprise:
    url: null                     # (required) the base url of your Github Enterprise ex. https://enterprise-hostname.com
    client_id: null               # (required) from https://github.com/settings/applications/new
    client_secret: null           # (required) from https://github.com/settings/applications/new
    access_token: null            # used to post comments, statuses, etc.
    global_upload_token: null     # a secret string that is used as a global token for uploading reports
    api_url: null                 # (optional) the base url of your Github Enterprise API defaults to `url + "/api/v3"`

# Bitbucket
# ---------------------------------
bitbucket:
    client_id: null               #
    client_secret: null           #
    access_token: null            # (key:secret) used to post comments, statuses, etc.
    organizations: null           # List of teams. Users must be a member of at least one. (optional) (default all)
    global_upload_token: null     # a secret string that is used as a global token for uploading reports

# Gitlab
# ---------------------------------
gitlab:
    client_id: null              #
    client_secret: null          #
    access_token: null           # used to post comments, statuses, etc.
    organizations: null          # List of teams. Users must be a member of at least one. (optional) (default all)
    global_upload_token: null    # a secret string that is used as a global token for uploading reports

# Gitlab Enterprise
# ---------------------------------
gitlab_enterprise:
    url: null                    #
    client_id: null              #
    client_secret: null          #
    access_token: null           # used to post comments, statuses, etc.
    global_upload_token: null    # a secret string that is used as a global token for uploading reports
