version: "3"

services:

  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx.config:/etc/nginx/nginx.conf:ro
      - archive-volume:/archive
      # Enable SSL: https://docs.codecov.io/v4.3.0/docs/deploying-with-docker#section-enable-ssl
      # - ./codecov.crt:/etc/nginx/codecov.crt:ro
      # - ./codecov.key:/etc/nginx/codecov.key:ro
    links:
      - web
      - monitor
    depends_on:
      - web
      - monitor
    ports:
      - "80:80"
      - "443:443"

  web:
    image: codecov/enterprise:latest
    command: /bin/run web
    ports:
      - "5000"
    volumes:
      - ./codecov.yml:/config/codecov.yml:ro
      - archive-volume:/archive
      # Enable provider SSL: https://docs.codecov.io/docs/deploying-with-docker#section-adding-ssl-pem-for-your-git-provider
      # - ./github_enterprise.pem:/config/github_enterprise.pem:ro
    links:
      - redis
      - postgres
    depends_on:
      - redis
      - postgres

  worker:
    image: codecov/enterprise:latest
    command: /bin/run worker
    volumes:
      - ./codecov.yml:/config/codecov.yml:ro
      - archive-volume:/archive
      # Enable provider SSL: https://docs.codecov.io/docs/deploying-with-docker#section-adding-ssl-pem-for-your-git-provider
      # - ./github_enterprise.pem:/config/github_enterprise.pem:ro
    links:
      - redis
      - postgres
    depends_on:
      - redis
      - postgres

  monitor:
    image: codecov/enterprise:latest
    command: /bin/run monitor
    # Uncomment below to enable http basic auto to access monitor interface
    # environment:
    #   BASIC_AUTH: "foo:bar"
    volumes:
      - ./codecov.yml:/config/codecov.yml:ro
    ports:
      - "5000"
    links:
      - redis
      - postgres
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:3.0.7-alpine
    volumes:
      - redis-volume:/data

  postgres:
    image: postgres:9.3
    volumes:
      - postgres-volume:/var/lib/postgresql/data

volumes:
  postgres-volume:
  redis-volume:
  archive-volume:
