version: '2'

services:

  nginx:
    # https://hub.docker.com/r/library/nginx
    image: nginx
    volumes:
      - ./nginx.config:/etc/nginx/nginx.conf:ro
      # - ./codecov.crt:/etc/nginx/codecov.crt:ro    # Enable SSL: __doc__
      # - ./codecov.key:/etc/nginx/codecov.key:ro    # [cont] Enable SSL
    links:
      - web
    ports:
      - "80:80"
      - "443:443"

  web:
    image: codecov/enterprise:dockerstore
    entrypoint: /bin/run web -p 8080 --name web.1
    ports:
      - "8080"
    volumes:
      - ./codecov.yml:/config/codecov.yml:ro
    links:
      - redis
      - postgres

  worker:
    image: codecov/enterprise:dockerstore
    entrypoint: /bin/run worker --name worker.1
    volumes:
      - ./codecov.yml:/config/codecov.yml:ro
    links:
      - redis
      - postgres

  redis:
    # https://hub.docker.com/r/library/redis
    image: redis:3.0.7

  postgres:
    # https://hub.docker.com/r/library/postgres
    image: postgres:9.3
