version: '2'

services:

  nginx:
    # https://hub.docker.com/r/library/nginx
    image: nginx:stable-alpine
    volumes:
      - ./nginx.config:/etc/nginx/nginx.conf:ro
      # - ./codecov.crt:/etc/nginx/codecov.crt:ro    # Enable SSL: https://docs.codecov.io/v4.3.0/docs/deploying-with-docker#section-enable-ssl
      # - ./codecov.key:/etc/nginx/codecov.key:ro    # [cont] Enable SSL
    links:
      - web
    ports:
      - "80:80"
      - "443:443"

  web:
    image: codecov/enterprise:beta
    entrypoint: /bin/run web
    ports:
      - "5000"
    volumes:
      - ./codecov.yml:/config/codecov.yml:ro
      # - ./github_enterprise.pem:/config/github_enterprise.pem:ro       # Enable provider SSL: https://docs.codecov.io/docs/deploying-with-docker#section-adding-ssl-pem-for-your-git-provider
      # - ./archive:/archive                                             # Enable report archiving: https://docs.codecov.io/docs/deploying-with-docker#section-enable-report-archiving
    links:
      - redis
      - postgres

  # web2:  # Ready to scale? https://docs.codecov.io/docs/deploying-with-docker#section-scaling-nodes

  worker:
    image: codecov/enterprise:beta
    entrypoint: /bin/run worker
    volumes:
      - ./codecov.yml:/config/codecov.yml:ro
      # - ./github_enterprise.pem:/config/github_enterprise.pem:ro       # Enable provider SSL: https://docs.codecov.io/docs/deploying-with-docker#section-adding-ssl-pem-for-your-git-provider
      # - ./archive:/archive                                             # Enable report archiving: https://docs.codecov.io/docs/deploying-with-docker#section-enable-report-archiving
    links:
      - redis
      - postgres

  # worker2:  # Ready to scale? https://docs.codecov.io/docs/deploying-with-docker#section-scaling-nodes

  redis:
    # https://hub.docker.com/r/library/redis
    image: redis:3.0.7

  postgres:
    # https://hub.docker.com/r/library/postgres
    image: postgres:9.3
